
services:
  spring-app:
    container_name: spring-app-dev
    build:
      context: .
      dockerfile: Dockerfile.dev  # [기본] 개발용 Dockerfile 사용
    ports:
      - "8081:8081"
    volumes:
      - .:/app             # [기본] 소스 코드 수정 시 자동 반영 (Hot Reload)
    environment:
      - SPRING_PROFILES_ACTIVE=dev # [기본] 개발 프로필 적용
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: hsj
      POSTGRES_PASSWORD: runner12
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: hsjking0403@naver.com
      PGADMIN_DEFAULT_PASSWORD: runner12
    depends_on:
      - postgres

volumes:
  postgres_data: